name: WPF Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Выдаем права нашему боту на создание релизов в репозитории
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' 

    - name: Restore dependencies
      run: dotnet restore Friday.csproj
      
    - name: Build
      run: dotnet build Friday.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish Friday.csproj -c Release -o ./publish /p:UseAppHost=true

    - name: Zip the application
      run: Compress-Archive -Path ./publish/* -DestinationPath ./Friday-App.zip

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: build-${{ github.run_number }}
        name: "Dev Build #${{ github.run_number }}"
        files: ./Friday-App.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
